name: Build and Push Docker Image

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup do Docker
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build da imagem Docker
    - name: Build Docker image
      run: docker build -t thamysgc/fintechx:latest .

    # Push da imagem para o Docker Hub
    - name: Push Docker image
      run: docker push thamysgc/fintechx:latest
